import { defineConfig } from "vite";

export default defineConfig({
  build: {
    lib: {
      entry: "electron/main.ts",
      formats: ["es"],
      fileName: () => "main.js",
    },
    rollupOptions: {
      external: [
        "electron",
        "@picovoice/eagle-node",
        "ffmpeg-static",
        "dotenv",
        // Node built-ins
        "node:fs",
        "node:path",
        "node:module",
        "node:child_process",
        "node:os",
        "node:crypto",
        "node:url",
        "node:http",
        "node:http2",
        "node:https",
        "node:net",
        "node:stream",
        "node:tls",
        "node:zlib",
        "node:buffer",
        "node:events",
        "fs",
        "path",
        "child_process",
        "os",
        "crypto",
        "url",
        "module",
        "http",
        "http2",
        "https",
        "net",
        "stream",
        "tls",
        "zlib",
        "buffer",
        "events",
      ],
    },
    outDir: ".vite/build",
    emptyOutDir: false,
    minify: false,
    sourcemap: "inline",
  },
});
