import { writeFileSync, existsSync } from "fs";
import { resolve } from "path";
import { execSync } from "child_process";
import { createInterface } from "readline";
import { PlaudClient } from "../plaud/client.js";

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

function askRequired(question: string): Promise<string> {
  return new Promise((resolve) => {
    const prompt = () => {
      rl.question(question, (answer) => {
        if (answer.trim()) {
          resolve(answer.trim());
        } else {
          console.log("  This field is required.");
          prompt();
        }
      });
    };
    prompt();
  });
}

export async function runInit(): Promise<void> {
  console.log("PlaudeNoteTaker Setup\n");

  // Check ffmpeg
  console.log("Checking dependencies...");
  try {
    execSync("ffmpeg -version", { stdio: "ignore" });
    console.log("  ffmpeg: OK");
  } catch {
    console.error(
      "  ffmpeg: NOT FOUND — install with `brew install ffmpeg`",
    );
    process.exit(1);
  }

  // Check for existing .env
  const envPath = resolve(process.cwd(), ".env");
  if (existsSync(envPath)) {
    const overwrite = await ask(
      "\n.env already exists. Overwrite? (y/N): ",
    );
    if (overwrite.toLowerCase() !== "y") {
      console.log("Keeping existing .env");
      rl.close();
      return;
    }
  }

  // Plaud bearer token
  console.log(`
── Plaud Bearer Token ──
To get your token:
  1. Open https://app.plaud.ai in your browser
  2. Log in to your account
  3. Open Developer Tools (Cmd+Option+I)
  4. Go to the Network tab
  5. Refresh the page
  6. Click any request to api.plaud.ai
  7. Copy the "Authorization" header value (without "Bearer " prefix)
`);
  const plaudToken = await askRequired("Plaud bearer token: ");

  // Test Plaud connection
  console.log("  Testing Plaud connection...");
  const plaudClient = new PlaudClient(plaudToken);
  const connected = await plaudClient.testConnection();
  if (!connected) {
    console.error("  Failed to connect. Check your token and try again.");
    rl.close();
    process.exit(1);
  }
  const devices = await plaudClient.listDevices();
  console.log(
    `  Connected! Found ${devices.data_devices.length} device(s): ${devices.data_devices.map((d) => d.name).join(", ")}`,
  );

  // AssemblyAI
  console.log("\n── AssemblyAI (transcription + diarization) ──");
  console.log("  Get an API key at https://www.assemblyai.com/dashboard");
  const assemblyAiKey = await askRequired("AssemblyAI API key: ");

  // Gemini
  console.log("\n── Google Gemini (note summarization) ──");
  console.log(
    "  Get an API key at https://aistudio.google.com/apikey",
  );
  const geminiKey = await askRequired("Gemini API key: ");
  const geminiModel = await ask(
    "Gemini model (default: gemini-2.5-flash): ",
  );

  // Picovoice
  console.log("\n── Picovoice Eagle (speaker recognition, optional) ──");
  console.log("  Get an access key at https://console.picovoice.ai");
  const picovoiceKey = await ask(
    "Picovoice access key (press Enter to skip): ",
  );

  // Vault path
  console.log("\n── Obsidian Vault ──");
  const vaultPath = await askRequired(
    "Absolute path to your Obsidian vault: ",
  );
  if (!existsSync(vaultPath)) {
    console.warn(`  Warning: path "${vaultPath}" does not exist yet`);
  }
  const notesFolder = await ask(
    "Notes subfolder (default: Meeting Notes): ",
  );

  // Templates
  console.log("\n── Templates (optional) ──");
  const templatesPath = await ask(
    "Path to custom templates folder (press Enter to use built-in default): ",
  );

  // Write .env
  const envContent = `# PlaudeNoteTaker configuration
# Generated by 'plaude init'

# Plaud device access
PLAUD_BEARER_TOKEN=${plaudToken}

# AssemblyAI (transcription + diarization)
ASSEMBLYAI_API_KEY=${assemblyAiKey}

# Gemini (LLM summarization)
GEMINI_API_KEY=${geminiKey}
GEMINI_MODEL=${geminiModel || "gemini-2.5-flash"}

# Picovoice Eagle (speaker recognition)
PICOVOICE_ACCESS_KEY=${picovoiceKey}

# Obsidian vault
VAULT_PATH=${vaultPath}
VAULT_NOTES_FOLDER=${notesFolder || "Meeting Notes"}

# Templates
TEMPLATES_PATH=${templatesPath}
SELECTED_TEMPLATE=Default

# Polling interval in seconds
POLL_INTERVAL=60

# Local state directory
DATA_DIR=./data
`;

  writeFileSync(envPath, envContent);
  console.log(`\nConfiguration saved to ${envPath}`);
  console.log('Run "plaude start" to begin polling for recordings.');

  rl.close();
}
